
const int charsPerLineEC = 201;   // this is the max # of chars per line
const int num_linesEC = 50;  // this is the number of lines in the array
const byte epd_bitmap_EC [num_linesEC][charsPerLineEC] = {                                                                                                                                                                                                    "          ",                                                                                                                                                                                               
"                                                                   Loanding .....                                                 ",
"                                                                                                                                  ",
"                                                                #NuevoOrdenBugcon2022                                             ",
"                                                                                                                                  ",                                                                                                                              
"                                                                                                                                  ",                                                               
"                                                                          ...                                                     ",                                                                
"                                                                         .....                                                    ",                                                                
"                                                                        ..   ..                                                   ",                                                                
"                                                                       .      ...                                                 ",                                                                
"                                                                      .        ...                                                ",                                                                
"                                                                     .          ...                                               ",                                                                 
"                                                                .';codxkkkkkxxdlccc,.                                             ",                                                               
"                                                             'cdkk0XKdxXKo::l0WNO0Kxolc'.                                         ",                                            
"                                                          .ckOxc,'cX0,.oKOooxXNo.:XXdokOko,.                                      ",                                            
"                                                         :kkc.  . .dNk'.,ldddl, .xWO,.;;:d0Ol.                                    ",                                            
"                                                        '0K;   .   .lKKd:'...';o0Xk,  .,..'dXK:                                   ",                                             
"                                                         :O0l..      .:dkOO0000ko,.    .,;ckKx'                                   ",                                            
"                                                          .lkOd;.        ......      .;okkkd;.                                    ",                                             
"                                                            .,lxkxoc;'..........,:ldk00ko;,..       ;o'                           ",                                             
"                                                                .,codxxxxkkkkOOOOkdl:,.    ...     .ck;                           ",                                             
"                                                                      ...........           ....  .,oOo'.                         ",                                             
"                                                                                        .;loxkkxddONMMMNO:..,c,                   ",                             
"                                                                                     .cxOkdolccclox0NMMMMNd;ld;                   ",                             
"                                      :OOOOOOxo' ,xOx,  'xOx'  ,oxkkkdc.    .;oxOOkdx0Oo;'..',,'...,:dKWMWKOOx'  ,kOo.            ",                             
"                                     .dWMNOkKWM0,:XMX;  ;XMX;.dNMXkx0NM0' .ckWMXkkXMNx,.'.  .,'.  .,'';xNXNMMWk. cNMO.            ",                             
"                                      dWMK, cNMX::XMX;  ;XMX;:NMNl  .dKO, lXWMX: ;KMNO;.....,;:,..',,'''dNMMMWWd.cNMK;            ",                             
"                                      oWMXo:OWWx.:XMX;  ;XMX:lWMK,  ..'...dWWM0'.kXOdc.    'dKX0l..... .,OMMWNWXllXMWl            ",                             
"                                     .oNMWK0XWWOccKWKl. ;XMX:lWMK,'xO000d,xWMWk.,0k;,,.   .;OWXl.     ..'dWMN0XN00KWWo            ",                             
"                              .:lcc:,'lKMK:'lXMMKx0WKl..lNWOlOWMX:.,cKW0:,OMMWk.'Oklkk:'.'';lxc       ',,xWMNooNMWMMNc            ",                             
"                             :xl,'';lld0WK;.cXMMOc0MWl ,KMMXooKMMk. 'OWk.'kKNMK,.dKKWXl;cdkKOc..     .,,cKMMN:.xWMMWK;            ",                             
"                            :x;.,..,;lxxkK0kXMMWd'dWMNO0NMXx,.kWMN0k0NMO. 'cxKNKk0WMWNKKNMMMk,......,ccl0WMMO' ;KMMW0,            ",                             
"                           .dl.,;.,dOkxxxxkkkxxd, ,xkkkkkk:   ,llccccll;   .,ldkkkxONMMMMMMNo.   .',lKNXkdxkc. .:cccc.            ",                             
"                           .cllo',xOxl:;,..,.                                      .:kXWMMMK:.   .;cxKk:..;c,..                   ",                             
"                             .:c;:c;'.. ..;'.                                        .,lkKXKxolldxxdl,    .co;..                  ",                             
"                                      ..':'                                              .';:cc:;'.        .cd:..                 ",                             
"                                     ..;c'                                                                  .:xl...               ",                             
"                                   ...:l'                    'cll;   ;ll:.   ;llc'  ,cll,                    .;xo'..              ",                             
"                                  ...ll'                     ','d0, lO:,kx. .,',Ok. ',,x0'                     ,do'..             ",                             
"                                 ..,ol.                       'ox:. dO..dk.  .;dd,   ,ox;                       'ol'..            ",                             
"                                ..;dl.                       :kOdc. .oooo,  .lOko;..:OOd:.                       .:c'..           ",                             
"                              ...:xc.                         ....    ..     .....   ....                         .,:'..          ",                            
"                             ...lkc.                                                                               .';'..         ",                     
"                            ..,dOc.                                                                                 ..,'..        ",                     
"                          ...:OKo'..............                                                                     ..,,..       ",                    
"                          .'lKKo;;,''...''.'....................                                                    ....,'..      ",                     
"                         ..lKXdccccccclllooooolllccc:::;;;,,,'''.........................................................'..      ",                     
"                         .;k0OOOOOOOOOO000000000OOOkkkkxxxdddooolllccc:::;;;;;;;,,,,,''',,,,,,,,,,,,,''''''''................     ",                     
"                          ......''''''',,,,,,,,,,,'''''..............                                                             ",       
};

const int charsPerLineCheems = 120;   // this is the max # of chars per line
const int num_linesCheems = 160;  // this is the number of lines in the array
const byte epd_bitmap_Cheems [num_linesCheems][charsPerLineCheems] = {  
"  `````````````````````````` ``.:,`  `````````````````````````````````````````````````````````````````````````````",
"                           `*zz##;```   ``                                                                      ",
"  `  `              ````   ,z#####*i;;:::::,.``      ````  ``` `   `  `   `  `   `  `  ``  `   `  `   `  `   `  ",
"`````````````````````````` i###+####+#+++++++++**iii;,``   `   `````````````````````````````````````````````````",
" `` ```````` ``` ````````` +#+########++#+##############+*i;:.` `  ```````````````````````````  ```````````` ```",
"  `   ```    ``     ` `` ` +++##################znnzzzzz####zz+,   ``   ` ``  ```    ```    ```    ```    ```   ",
"                         `.+++################zznxxnzzz#+####zzzi``                                             ",
"``` ```````` ` ````````  .*++##########zzz###zzznxxnnnz##zzz##zzn;    ``````````````````````````````````````````",
"  `   ```    ``     `  `.++++######z#z#z#####zzzznxxxn##zzzz###nnn;` `  ` ``  ```    ```    ```    ```    ```   ",
"             `        `.***++#zzz##########z##zzzznxnz#zzznzz##nxxn+.                                           ",
" `````````  `````` ````i***+#zzzz#########z###zzz#znnzz#znnnnz#zxxxz#: ``` `````` `````` ```````````````````` ``",
"  `         `  `    ``;****+#zzzz############z#zz##zn###znxxnn##nxxnn#.``   ` ``  `` ``  `` ``  `` ``  `` ``  ``",
"             `       ,*i***+zzzzz##############zzz##z####nnnnz##zxMxnn*` `                                      ",
" `````````  ``````  `i;;i**#znz######+#########zzz###zz#zz#znz##znMxxnz:`  `````` `````` ```````````````````` ``",
"  `         `  `   `,+ii**+#zzz###+++++########zzzz###zz####n#++zxMxxnnz,   ` ``  `` ``  `` ``  `` ``  `` ``  ``",
"             `      i#ii**+##z###+++++#########zzzzz##zzzz##z#+#nxMxxnnz#.                                      ",
" `````````  `````` `*z*ii*++#+#++++++*+++###z#z#zzzzz#zzzzzzz#z#zxMxxnnnz;   ```` `````` ```````````````````` ``",
"  `         `  `   ,xz+i**+#+#+++++#+*****####zzzzzzz##znnzzz##+nMMMxnnnz+`   ``  `` ``  `` ``  `` ``  `` ``  ``",
"             `     iMMz***+++++*+#zz#++++**+#z#zzzzzz###znznnnnzxMMxxnnnzzi                                     ",
" ``` `````` ```` ` *MMn**+++++*++#zxxxxnnnnzzzzzzzzzz###znnnnxxxMMMxnnnzzzz.```````````` `````` `````` `````````",
"  ` ```      `   ` +MM#+++++++#znMWMWWMWWWxzz#zzz##zz####znnnnxMxxxnnnzzznzi ``` `````` `````` `````` `````` ```",
"                  `+zz########nxxMWWWWWMMz*i***+#########znnnnnnnxxnnnzzzzzz.                                   ",
"````````````````  .##zzzzznnnxxn###znnnz*iiii;ii*++#######znnzznnnnnnnzzzznz;  ````````````````````````````` ```",
"  ` ```      `  ` ,#zzzznnnnxxn#+**++++***ii;;:;i*++#####zzzzzzznnnnnnzzzzzz+``` `````` `````` `````` `````` ```",
"                ` :znnnxxnnnnnn#*********i;;::::;i*++####zzzzzzzzzzzzzzzzznzz:                                  ",
"```````````````` `*nnxxxnnnnnz#+*i;iiiii;;;:,,,:;ii++####z#zzzzzzzzzzzzzzzzzz#`````````````````````````````` ```",
"  ` ```      `  `innxxxxnnnzz#+**i;;;;;::::,,,,,;;i**++###zzzzzzz#zzzzzzzzzzzz*` `````` `````` `````` `````` ```",
"               `*nnxxxxnnnz###+**i;;:::::,,,,,,,;;ii**++####zzzzzzzzzz###zzzznn+`                               ",
"```````````   `+nnxMxxnzz##++++**i;;::::,,,,,,,,:;i***++####zz#z####z####zzzzznni`  ```````````````````````` ```",
"  ` ```      `*nxxxMxxnz##+++++*ii;;;:;::,,,,,,,::;ii***++#z#####z#zz####zzzzznnz;` ``` `````` `````` `````` ```",
"             inxMMMxxxnnz#++++++*i*iii;;::,,,,,,,:;;ii***+########zzz##zzzzzzznnzz*`                            ",
"``````````` :MMWWWWMxnz+++++++++*+++*ii;;:::,:::::;;;ii**++#####zzzz####zzzzzzzzzzz+.`   ``````````````````` ```",
"  ` ```   ` zMWWWWWWWxz++*+#+##+*+###+*i;::::::;;;;i;ii*+++####zzzzz###zzzzzzzzzzzzz#,```````` `````` `````` ```",
"           .MWWMWWWWWMz++#+*++##+#nz#+*ii;;i;;;;iiiii****+####zzzzzzzzzzzzzzzzzzzzz#zz*.                        ",
"`````````` :MWWWWWWWWxz##*+++++#zxxnz#+iii;ii;:;;;;ii**+++###zzzzzzzzzzznzzzzzzzzzzzzz##:` ````````````````` ```",
"  ` ```    `MWWWWWWWMn###+**++##nxMMnz#*i;:::;::;;iii**++++#zzznnzzzzzzznzzzzzzzzzzz#####;```` `````` `````` ```",
"           `*WWWWWWMxn#+++++#zznxWMxn#++i;::::;;;iii*+++++###z#zzzzzzznnnnzzzzzzzzzzzzz###;`                    ",
"``````````` `+xMMMxxxz#+#+#zzznMWMxn#++*i;:::::;ii;i***+++##zzzz#zzzznnnzzzzzzzzzzzzz###zz#;` `````````````` ```",
"  ` ```     `.*nxxxMxxz##zzzzxMMxnz##++ii;:::::;;ii***++++#z##zzzzznnnnnzzzzzzzzzzzz##z##zz#;`  ````` `````` ```",
"               .inxxxxxxxnnnxMxn#####+ii;::::;:;;ii***+++#####zzzznnnnnnzzzz#zzzzzz#zz###zzz#:                  ",
"``` `````````` ````,::i#zzznnn####++*ii;;::::::;ii***+++#####zzzzzznnnnnzzzzz##zzzz#z#zzzz####,   ``````````````",
"  `  `` `   ``         ;#zzzz###++**i;;;:::::;;iii*+++++###zzzzzznznnnnzzzzz###zz######z###zz##.  ` ``   ` ``   ",
"                       `+#######+*iii;;;;::;;;;ii**+++###zzzznnzznnnnnzzzzzzzzz####zz###zzzzzz#+`               ",
"``` `````````````````   i++++++**i;;;;;;;;;;;iiii****####zzzznzzznnnnnnzzzzzzz###zzzzzzzzzznz###i```````````````",
"  `  `` `   ``       `` ;*+++**ii;;;i;;;;;;;;iii****+###zzznnzzznnnnnzzzzzz##zz#zzzz#z###znnnzz##,` ``   ` ``   ",
"                        :iiiiii;;;;;;;;;;;;;;iii**++###zzznzzzzznnnnzzzzz###zz##z######zznnnnnzz#+`             ",
"``` ``````````````````` :iiiiii;;;;;;;;;;;;;ii**++####zzzzzzzzznnnnzzzzzz###zzzzzzz#zzzznnnnnnnnzzi  ```````````",
"  `  `` `   ``       `` :iiiiii;;;;;;;;iiiiii*++++##zzzzzzzzzznnzzzzzzz#######zzzz#z###znnnnnnnnnz#. `   ` ``   ",
"                        :iiiiii;i;;;;;iiiii***++++#zzzzzzzzzznnnzzzz################zzznnnnnnnnnnz#i`           ",
"``` ````````````````````:;;;iiiiii;;;iiii*****+++##zzzzzzzzzzzzzz####################znnnnnnnnnnnnzz.```````````",
"  `  `` `   ``         `:;;;;;;;;;;;;;;iii*****++####z##zzzzzz#zz####################znnnnnnnnnnnnzz;`   ` ``   ",
"                       `:;;;;;;;;;;;;:;;ii***++++#######z#z###z#####+++#++#########znxxnnnnnnnnnnnzz+`          ",
"``` `````````````````  `:;;i;;;;;;;;;;;;;;i***++++++############++++++++++++####zzzznxnnnnnnnnnnnnzzz. `````````",
"  `  `` `   ``       ```::;;;;;;;;;;;::;;;;i****+*+++####++++++++++++*+++++######zznxnnnnnznnnxnnnzzz,   ` ``   ",
"                      ``::;;;;;;;;:::::::;;ii******++###+++*+++++*******+++####zznnnnnnnnznnnnxnnzzzzi          ",
"``` `````````````````` `::;:;;;;;;;;::::::;ii****+*++++*++***********+++++++###znnnnnnnnnnnnxxxnnzzzz+``````````",
"  `  `` `   ``       `` ,:;;;;;;;;;;;:::::;;;iii************iiii*****+*+++###zznnnnnnnznnnnxxxnnnzzzzz,` ` ``   ",
"                        ,:;;;;iii;;;;::::::;;iii*********iiiiii********+++##zzznnnnnnnnznnnxxxnnnzzzzz*`        ",
"``` ``````````````````` ,::;;;;ii;;;;::::::;;iii*****i*iiiiiiiii*****+*+++##zznzzzzzznnnnnxxxnnnzzzzzzz.  ``````",
"  `  `` `   ``       `` ,:::;;;;;;;;;:::::;;iiiiiiiiiiiiiiiiiiii*****++#+##zzzzzzzzzznnnnxxxnnnnzzzzzzn:   ``   ",
"                       `::::;;;;;;;;:::::::;;iiiiiiiiii;iiiiiiii*****+++####zzzzzzznzznnxxxxnnzzzzzzzzn+`       ",
"``` ````````````````````::;;;;;;;;;;;::::::;;;;iiiii;;;;;;iii*****++++++######zzzzzznnnnxxxnnnzzzzzzznnn. ``````",
"  `  `` `   ``       ```::;;;;:;;;;;::::::::;;;;;;;;;;;iiiiii**+*+++++##########zzzzzznnMxxnzzzzzzzzzznx*   `   ",
"                      ``::;;;;:::;;::::::::::;;;;;;;;;iiii******+++++++++#++###zzzzznnnxMxnnzzzzz#zzzznxn`      ",
"``` ````````````````````,:::::::;;;;;;;;;;::::;;;;;;iiii*****+**++++++++*++####zzzzznnnxMxnnzzzzzzzzznnxM;  ````",
"  `  `` `   ``       ` `::::::::;;;;;;;;;;::::;;;iiiiii**********+++******+++#zzzzzznnnxxxnzzzzzzzzznnxxxn```   ",
"                      ``:;;;::::;;;;;;;;;;;;;;;;iiiiii**i******************+##zzzzzznnxxxnnzzzzzzzzznnxxxx:     ",
"``` `````````````````` .;;;;:::::::;;;;;;;;;;;;;;iii*iiiiiiiiii******ii*i*++##zzzzznnnnxxnnzzzzzzzznnxxxxx#`````",
"  `  `` `   ``       ` .;;;;;:::::::;;;;;;;::::;;;iiiiiiiiiiiiii*iii*ii***++##zzzzznnnxxxnnzzzzzzznnnxMxxxx,    ",
"                       .;;;;i;;:::;;;;;;;;;;;;;;;;ii;;;;;;;;;i;iiiiiiiii**++#zzznnnnnnnxxnnzzzzzzzznxxxxxxx*    ",
"``` `````````````````` .;;;;i;;;;;;;;;;;;;;;;iiii;iiii;;;;;;;;;;iiiiiiii**+#zzzzzznznnnxnnzzzzzzzznnxxxxxxxz` ``",
"  `  `` `   ``       ` .;;;;iiii;;;;;::::;;;;;;;;;;i;i;;;;;;;;;;;;;;;;ii**+#zzzzzznnnnnnnzzzzzzzzznxxxxxxxxn.   ",
"                      `.;;;;iiiiii;;;:::::;;;;;;;;;;;;ii;;;;;;;;;iiiiiii*+#zzzzzznnnnnnnnzzzzzznnnnxxxxxxxnz:   ",
"``` ````````````````````;;;;iiii*ii;;::::;;;;;;;;;;;;iii;;;;;;;;;;iiii**+#zzzzzzzzznnnnnnzzzzzznnnnxxxxxxnnz; ``",
"  `  `` `   ``       ```;;;;iiiiiiii;:;;;;;;;;;;;;;;;;iii;;;;;;;;;iiii*+#zzzzzzzznnnnnnnnzzzzznnnnxxxxxxnzzz*   ",
"                        :iiiiiiiiii;;;;;;;;;;;;;;;;;;ii;i;;;;;;;i;iii*+##zzzzzzznnnnnnnnzzzzzzznnnnnxxnnnzzz+   ",
" ``  ` `` ` ` `` ` ```` :iiiiiiiiiii;;;;;;;;;;;;;;;;;;iii;;;;;;;iiiii*+zzzzzzzzzznnnnnnzzzzznnnnnnnxxnnnnzznz```",
"  ` ``` `    ` `    ` ` ,i********ii;;;;;;;;;;;;;;;;;ii;;i;;;;;;iii**++#zzzzzzzznnnnnnnzzzzznnnnnnnnnnnnnnnnz` `",
"  `  `                ` ,i**++++***ii;;;ii;;;iiiiiiiiiiiiii;;iiiii**+++#zzzzzzzznnnnnnnnzzzznnnnnnnnnnnnnnnnn`  ",
"  ` ``````` ```` `   `` .**+++++++**ii;;;;;iiiiiiiiii**iiiiiiiii****+#zzzzzzzzzznnnnnnnzzz#znnnnnnnnnnnnnnnnx.``",
"  ` ``` `    ` `    ` ` `*****++++**iii;;;iiiiiiiiiiiiiiiiiiiiii***++##zzzzzznnnnnnnnnnzzzzznnnnnnnxnnnnnnnnz` `",
"  `  `                ` `*+**+*+++++*ii;;;iiiiiiiii********ii***++++##zzzzzzznnnnnnnnnznzznnznnnnnnxxnnnnnnn+`  ",
"  ` ``````` ```` `   `` `++++****+++**i;;;;ii****i**********i***+++##z#zzzzznnnnnxnnnzzznnnzznnnnnnnnnnnnnnn* ``",
"  ` ``` `    ` `    ` ` `+++***********ii;;;ii*****************++###zzzzzznnnnznnxnnnnzzznnnnznnnnnnnnnnnnnn:  `",
"  `  `                ` `+++***********iii;;iii***************+++###zzzzzzzznnnnnnnnnnnnznzznnnnnnnnnznnnnnn.`  ",
"  ` ``````` ```` `   `` `+++************iiiiiiiiii***********+######zzzzzzzzzzznnnnnznnnzzznnnnnnnnnnnnnnnnz` ``",
"  ` ``` `    ` `    ` ` `#++******i*******iiiiiiiii********+++#####zzzzzzzzzznnnxxnnnnnnzznnnnnnnnnxxxnxxnx+   `",
"  `  `                ` .#++****iiii*i*******iiiiiiii******+++###zzzzzzzzzzzznnnnxxnnnnnzznzznnnnnnnxxxxxxn*    ",
"  ` ``````` ```` `   `` .#++*****iii************ii*iiiii**++++###zzzz#zzzzznnnxxxnnnnnzznnnnnnxxnnnnxxxxxxx: ```",
"  ` ``` `    ` `    ` ` .#++****iiiii********++***ii*iii**++++##zzzz#zzzzznnnnxxxxnnnnnnznnnnxxnnnnnnnnnnnz`   `",
"  `  `                ` `#+******iiii*******++*+******ii*+++++##zzzzzzzzznnnxxxxxxnnnnnnnnnxxxxnnnnnnnnnnn;     ",
"  ` ``````` ```` `   `` `#+*****iii;ii**+*+*+++************+++##zzzzzzzzznnnxMxxxxnnnnnnnnnxxxxnnnnnnnnnn#` ````",
"  ` ``` `    ` `    ` ` `#+***iiiiiiii*+++++++*+*****+++***++++##zzz#zzzznnxMMMxxxnnnnxnxxxxxxnnnnnzznnnn,     `",
"  `  `                ` .++***iiii;;ii*+#z###+++++++++++*****++####zzzzzzznxMMMxxxxxnxxxxxxxxnnnnnnnnnnn;`      ",
"  ` ``````` ```` `   `` .++*iiiii;;;;i*+zznzz##++##++++++****++####zzzzzzznxxMMMxxxxxxxxxxxnnnnnnnnnnzn+` ``````",
"  ` ``` `    ` `    ` ` ,++*iiii;;;;i**#znxxz##++###+++##+***++####z##zzznnxxMMMMMxxxxxxnxxnxnnnnnnnnnn,   `   `",
"  `  `                ` ,++**iiii;;;i*+#znxxnz#++#########***++#####z#zzzznnxMMMMMMMxxxxxxxnnnnnnnxnnx+`   `    ",
"  ` ``````` ```` `   `` ,*+*iiii;;;;i*##zxMMxn##+###++####+**++#######zzznnnxMMMMMMxxxxxxxnxnnnxnnxxnn.`````````",
"  ` ``` `    ` `   `    ,i+*iiiii;;ii+#znxxMMxn##++++++###+***++######zzzznnxMMMMMMxxxxxnxnxnnnxxxnxn;     `   `",
"  `  `                .:;*+**iiii;ii*+#znxnxxxxz#+++++++##+***++#####zzzznnnxMMMMMMxxxnxxxxxnnnnnnnni`     `    ",
"  ` ```````   `     `:*ii++**iiii;ii*+znnnnnxxxn#++++++###+*i*++++####zzznnnxMMMMMMxxxxxxxxxnnnnxxx+`  `````````",
"  ` ``` `       `.,i++++*++*iiiii;ii*+znnnnnxxxnz++++++++#+***++++###z#zzznnxMMMMMMxxxxxxxxnnnnnxx#`       `   `",
"  `  `       `.:**++#++++#**iiiiii;i*#zxnnnxxxxnzz#++++++#+***+++#####zzznnnxMMMMMMxxxxxxxxxnxnnn+`        `    ",
"  `   `  `.,:i*++++######+*iiiiiii;i+zznnnnxMxxnzz###++++++i**+++++###zznnnnxMMMMMMMxxxxxxxxxxxni`   ` `````````",
"  `  ` `,;ii***++########+**i*i*iii*+zznxxxMMMz##++++++++#+****++####zzzzznnxMMMMMMxxxxxxxxxxMn:``  `      `   `",
"   ` `,iiiiii**+#zz####zz+**i*i*iii*#zznxxMMnz#+++*+****+*****+++####zzzzzznxMMMMMMMMxxxxxxxxn,            `    ",
"    `;iiii***+###zzz##*;;**i***i*ii+##znxxnz#++++*************+++###zzzzzznnxMMMMMMxxxxxxMMMz.  `````` `````````",
"  ``iii***#*+####zzz+,` `**i****ii*#z#znnzz#++**********ii****++###zzznnnnnnxMMMMMMMMMxxxMM+`    `  `      `   `",
"  `:##**+zz+##z#*;,`` ```**i****i*+#zznnzz#++**********iiii***+++###znnnnznnnxxMMMMMMMxxMx:`               `    ",
"   *Mz++zMx##i.`  `  `` `*****+**++#znzzz#++**********iiiii****++##zznnnzzznxxMMMMMMMxxxz.  `````````` `````````",
"   .#x#+xWM*`   `   ` ` .**i**++*+#zzzzz##+*****i*iiiiiiiii****+###zznnnnnnnxMMMMMMMMMx*` `  `   `  `      `   `",
"   ```  `:`           ` :+*****++##zzzzz#+****iiiiiiiiiiiii***+++##zznnnnnnxMMMMWWMMx#,                    `    ",
"      ``  ` ```` `     `*+*****+##znnnz#++***iiiiii;iiiiiii**+++###zznnnnnnxMWMWWMM#,`   ````````````` `````````",
"  ` ``` `    ` `    `` ,++*****+##znnnz#+*iiiiii;;;;;iiiiii**+++###zznnnnnxxMWWWWx;`` `   `  `   `  `      `   `",
"  `  `                ,++******+##znnz#+*iiiiiii;;iiiiiii****++###zzznnnznxMWWWxi`  ` `                    `    ",
"  ` ``````` ``     ``:#+*****++###znz#+*ii;iii;;;iiiiiii**+**++###zznnnznnxMWM*`    ```` ````````````` `````````",
"  ` ``` `    `  `.,i##++****+++##znzz+i;;;;;;;;;;iiii***+#+**++###zznnnznxxM#. `   `` `   `  `   `  `      `   `",
"  `    `    `,;*+####+******+++#+#zz#*;;;;;;;;iiii****++#z+*+++###zznnznnn*.`       ` `                    `    ",
"  `     `.:i*+######++*******+*` ``,,:::,..``.,:;;ii*++#zn#*++++##zznnnnn:` ```````````` ````````````` `````````",
"  ` `.,:i++++######+*********+.  ```            ```````:*n#*+++##zzznnnn;  ``  `   `` `   `  `   `  `      `   `",
"   `*z#++##+++####+**********:              `            `*++++##zznnnn+`           ` `                    `    ",
"  `;Mz#+*****+###+**********;`  ``` ``  `````` `````` ````;++++##zznnnz``  ````````````` ````````````` `````````",
"  .nMMn++****+##+ii****i*i*;``  ` ` `` ```    ``     ``` `:*+++#zzznxx:   ```  `   `` `   `  `   `  `      `   `",
"  ,nn#+*+***++*iiiiiii*iii;`                `             ,*+++##zznxz`             ` `                    `    ",
"  `+**++**++*****iiiiiiii:`` `````` ``  `````` `````` ``` .+++++##znx+     ````````````` ````````````` `````````",
"   ;++++*++*i******iiiii:` ` `` ` ` `` ```    ``     ```  `*++++##znx; `  ```  `   `` `   `  `   `  `      `   `",
"   `#++++*i**i*iii*****;`                   `             `*+++###zzn; `            ` `                    `    ",
"  `` `i***********+++:`  ` ` `` ` ` `` ```    ``     ``` `;*++####zzn; `  ```  `   `` `   `  `   `  `      `   `",
"  `   ;z+****++**+++:                       `            `i*++####znn;              ` `                    `    ",
"  `  `:#+ii*+#n#*++;` ````   `````` ``  `````` `````` ````**++###zznn*`    ````````````` ````````````` `````````",
"  `    `,i*+#z+*i:`` ``` ` ` `` ` ` `` ```    ``     ``` .++++###zznnz`   ```  `   `` `   `  `   `  `      `   `",
"  `  `   ```` `       `                     `            ,*+++###zznnz.             ` `                    `    ",
"  ` `````````  ` `   `````   `````` ``  `````` `````` ```,**++###zznnz`    ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``     `  `;*+++##zznnn+    ```  `   `` `   `  `   `  `      `   `",
"  `  `                `                     `          ``i+++###zznxn: `            ` `                    `    ",
"  ` ``````` ```` `   `````   `````` ``  `````` ``````  ``*++++#zzznxn`     ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``     ` `.*++++###znxz     ```  `   `` `   `  `   `  `      `   `",
"  `  `                `                     `          `,i**+++##znx+               ` `                    `    ",
"  ` ``````` ```` `   `````   `````` ``  `````` ``````   ,iii**+##zzni ``   ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``     ` `i***i**##zzz:     ```  `   `` `   `  `   `  `      `   `",
"  `  `                `                     `         `,i*****++#zzz.               ` `                    `    ",
"  ` ``````` ```` `   `````   `````` ``  `````` `````  .i****ii*+#zz#` ``   ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``    ``:********##zz+      ```  `   `` `   `  `   `  `      `   `",
"  `  `                `                     `        ,*********+#zz*                ` `                    `    ",
"  ` ``````` ```` `   `````   `````` ``  `````` ````` ;******++*+###:  ``   ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``   ``xz*****+#n#++;`      ```  `   `` `   `  `   `  `      `   `",
"  `  `                `                     `      `:Mn+*+**+zWn,`                  ` `                    `    ",
"  ` ``````` ```` `   `````   `````` ``  `````` ````` ,##zx#*++*.    ````   ````````````` ````````````` `````````",
"  ` ``` `    ` `    ` `` ` ` `` ` ` `` ```    ``      `,:#i,`      ```    ```  `   `` `   `  `   `  `      `   `",   
};
